"""Puerto de repositorio para Categoria."""
from __future__ import annotations

from typing import Optional, Protocol

from src.catalogo.domain.models.categoria import Categoria


class CategoriaRepository(Protocol):
    async def guardar(self, categoria: Categoria) -> Categoria: ...

    async def obtener_por_id(self, categoria_id: str) -> Optional[Categoria]: ...

    async def obtener_por_nombre(self, nombre: str) -> Optional[Categoria]: ...

    async def listar(self) -> list[Categoria]: ...

    async def actualizar(self, categoria: Categoria) -> Categoria: ...

    async def eliminar(self, categoria_id: str) -> None: ...

    async def contar_repuestos_usando(self, nombre: str) -> int: ...
