"""Puerto de persistencia del módulo taller (03 §8.1)."""
from __future__ import annotations

from typing import Optional, Protocol

from src.taller.domain.models.orden_trabajo import (
    Entrada,
    HistorialIntervencion,
    Mecanico,
    OrdenTrabajo,
    Vehiculo,
)


class TallerRepository(Protocol):
    async def guardar_ot(self, ot: OrdenTrabajo) -> OrdenTrabajo: ...
    async def obtener_ot(self, ot_id: str) -> Optional[OrdenTrabajo]: ...
    async def actualizar_ot(self, ot: OrdenTrabajo) -> OrdenTrabajo: ...
    async def listar_ots(self) -> list[OrdenTrabajo]: ...

    async def guardar_vehiculo(self, v: Vehiculo) -> Vehiculo: ...
    async def obtener_vehiculo(self, v_id: str) -> Optional[Vehiculo]: ...

    async def guardar_mecanico(self, m: Mecanico) -> Mecanico: ...
    async def obtener_mecanico(self, m_id: str) -> Optional[Mecanico]: ...
    async def listar_mecanicos_disponibles(self) -> list[Mecanico]: ...
    async def actualizar_mecanico(self, m: Mecanico) -> Mecanico: ...

    async def guardar_entrada(self, e: Entrada) -> Entrada: ...
    async def obtener_entrada_por_ot(self, ot_id: str) -> Optional[Entrada]: ...
    async def actualizar_entrada(self, e: Entrada) -> Entrada: ...

    async def guardar_historial(self, h: HistorialIntervencion) -> HistorialIntervencion: ...
