/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * EP-AUTH-01: Login con credenciales
         * @description Público — sin token.
         *     Bloqueo 15 min tras 10 intentos fallidos/IP (07 §2.5).
         *     InMemory: rate limiting simplificado.
         */
        post: operations["login_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/mfa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * EP-AUTH-02: Verificar MFA y obtener tokens
         * @description Semi-público — requiere mfa_session_token válido (TTL 5 min — 07 §2.4).
         *     En InMemory acepta cualquier código 6 dígitos.
         */
        post: operations["mfa_v1_auth_mfa_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * EP-AUTH-03: Rotar refresh token
         * @description Semi-público — requiere cookie refresh_token válido.
         *     Replay detection: reuso invalida familia completa (07 §2.3 Escenario 2).
         */
        post: operations["refresh_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * EP-AUTH-04: Cerrar sesión
         * @description Todos autenticados — revoca la sesión y elimina cookie (07 §2.3 Escenario 1).
         */
        post: operations["logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/parametros": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * EP-ADM-01: Listar parámetros del sistema
         * @description SUPERADMIN · ADMINISTRADOR — lista todos los parámetros configurables.
         */
        get: operations["listar_parametros_v1_admin_parametros_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/parametros/{clave}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * EP-ADM-02: Actualizar parámetro del sistema
         * @description SUPERADMIN · ADMINISTRADOR — actualiza un parámetro (ABAC-07: solo si modificable_por == ADMINISTRADOR).
         *     Invalida caché Redis DB-1 (InMemory: actualización directa).
         */
        patch: operations["actualizar_parametro_v1_admin_parametros__clave__patch"];
        trace?: never;
    };
    "/v1/admin/vehiculos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * EP-ADM-03: Registrar vehículo
         * @description SUPERADMIN · ADMINISTRADOR · VENDEDOR — registra un vehículo en el sistema.
         */
        post: operations["crear_vehiculo_v1_admin_vehiculos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/mecanicos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * EP-ADM-04: Registrar mecánico
         * @description SUPERADMIN · ADMINISTRADOR — registra un mecánico en el sistema.
         */
        post: operations["crear_mecanico_v1_admin_mecanicos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/usuarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * EP-ADM-05: Crear usuario
         * @description SUPERADMIN · ADMINISTRADOR — crea usuario.
         *     No puede crear SUPERADMIN (03 §6.6).
         */
        post: operations["crear_usuario_v1_admin_usuarios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repuestos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * EP-CAT-01: Buscar repuestos
         * @description Búsqueda por universo, modelo y año. NUNCA devuelve precio_venta.
         */
        get: operations["buscar_repuestos_v1_repuestos_get"];
        put?: never;
        /**
         * EP-CAT-03: Crear repuesto
         * @description Crea repuesto nuevo. Solo ADMINISTRADOR y SUPERADMIN.
         */
        post: operations["crear_repuesto_v1_repuestos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repuestos/{codigo}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * EP-CAT-02: Obtener repuesto por código
         * @description Obtiene repuesto por código. NUNCA devuelve precio_venta.
         */
        get: operations["obtener_repuesto_v1_repuestos__codigo__get"];
        put?: never;
        post?: never;
        /**
         * EP-CAT-05: Dar de baja repuesto (baja lógica)
         * @description Baja lógica — nunca eliminación física. Solo ADMINISTRADOR y SUPERADMIN.
         */
        delete: operations["dar_de_baja_repuesto_v1_repuestos__codigo__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repuestos/{codigo}/precio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * EP-CAT-02-B: Consultar precio
         * @description Único endpoint que expone precio_venta.
         *     Decrementa consultas_precio en sesión si rol CLIENTE_*.
         */
        get: operations["consultar_precio_v1_repuestos__codigo__precio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * EP-CAT-04: Actualizar precio de venta
         * @description Actualiza precio. Solo ADMINISTRADOR y SUPERADMIN.
         */
        patch: operations["actualizar_precio_v1_repuestos__codigo__precio_patch"];
        trace?: never;
    };
    "/v1/repuestos/{codigo}/historial-precio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * EP-CAT-06: Historial de precio
         * @description Historial de cambios de precio. Solo ADMINISTRADOR y SUPERADMIN.
         */
        get: operations["historial_precio_v1_repuestos__codigo__historial_precio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalogo/repuestos/consulta-lista": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * HU-S2-01: Consulta múltiple
         * @description Consulta múltiple por lista de códigos para CLIENTE_DISTRITO (HU-S2-01).
         */
        post: operations["consultar_lista_codigos_v1_catalogo_repuestos_consulta_lista_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stock/{codigo}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** EP-STK-01: Consultar stock por código */
        get: operations["consultar_stock_v1_stock__codigo__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** EP-STK-02: Listar todo el stock */
        get: operations["listar_stock_v1_stock_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stock/{codigo}/movimientos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** EP-STK-03: Historial de movimientos */
        get: operations["listar_movimientos_v1_stock__codigo__movimientos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stock/{codigo}/ajuste": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** EP-STK-04: Ajuste manual de stock */
        post: operations["ajustar_stock_v1_stock__codigo__ajuste_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stock/{codigo}/umbral": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** EP-STK-05: Actualizar umbral mínimo */
        patch: operations["actualizar_umbral_v1_stock__codigo__umbral_patch"];
        trace?: never;
    };
    "/v1/reabastecimientos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** EP-STK-06: Crear reabastecimiento */
        post: operations["crear_reabastecimiento_v1_reabastecimientos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reabastecimientos/{reab_id}/estado": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** EP-STK-07: Actualizar estado de reabastecimiento */
        patch: operations["actualizar_estado_reabastecimiento_v1_reabastecimientos__reab_id__estado_patch"];
        trace?: never;
    };
    "/v1/reabastecimientos/{reab_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** EP-STK-08: Obtener reabastecimiento */
        get: operations["obtener_reabastecimiento_v1_reabastecimientos__reab_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pedidos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** EP-PED-02: Listar pedidos */
        get: operations["listar_pedidos_v1_pedidos_get"];
        put?: never;
        /** EP-PED-01: Crear pedido */
        post: operations["crear_pedido_v1_pedidos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pedidos/{pedido_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** EP-PED-03: Obtener pedido */
        get: operations["obtener_pedido_v1_pedidos__pedido_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pedidos/{pedido_id}/confirmar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** EP-PED-04: Confirmar pedido */
        post: operations["confirmar_pedido_v1_pedidos__pedido_id__confirmar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pedidos/{pedido_id}/cancelar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** EP-PED-05: Cancelar pedido */
        post: operations["cancelar_pedido_v1_pedidos__pedido_id__cancelar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reservas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** EP-PED-06: Crear reserva */
        post: operations["crear_reserva_v1_reservas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reservas/{reserva_id}/liberar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** EP-PED-07: Liberar reserva */
        post: operations["liberar_reserva_v1_reservas__reserva_id__liberar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pedidos/{pedido_id}/proforma": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** EP-PED-08: Emitir proforma */
        post: operations["emitir_proforma_v1_pedidos__pedido_id__proforma_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pedidos/{pedido_id}/envio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** EP-PED-09: Registrar envío */
        post: operations["registrar_envio_v1_pedidos__pedido_id__envio_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pedidos/{pedido_id}/confirmar-recepcion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** EP-PED-10: Confirmar recepción */
        post: operations["confirmar_recepcion_v1_pedidos__pedido_id__confirmar_recepcion_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pedidos/{pedido_id}/incidencia": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** EP-PED-11: Registrar incidencia */
        post: operations["registrar_incidencia_v1_pedidos__pedido_id__incidencia_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notificaciones/repuesto-disponible": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** EP-PED-12: Solicitar notificación cuando repuesto esté disponible */
        post: operations["solicitar_notificacion_repuesto_v1_notificaciones_repuesto_disponible_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lista-reserva-progresiva": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** EP-PED-13: Crear lista de reserva progresiva */
        post: operations["crear_lista_reserva_v1_lista_reserva_progresiva_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lista-reserva-progresiva/{lista_id}/formalizar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** EP-PED-14: Formalizar lista de reserva progresiva */
        post: operations["formalizar_lista_reserva_v1_lista_reserva_progresiva__lista_id__formalizar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pedidos/{pedido_id}/comprobante": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** EP-PED-15: Generar comprobante */
        post: operations["generar_comprobante_v1_pedidos__pedido_id__comprobante_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/comprobantes/{comprobante_id}/aprobar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** EP-PED-16: Aprobar y emitir comprobante */
        post: operations["aprobar_comprobante_v1_comprobantes__comprobante_id__aprobar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/comprobantes/{comprobante_id}/anular": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** EP-PED-17: Anular comprobante */
        post: operations["anular_comprobante_v1_comprobantes__comprobante_id__anular_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ordenes-trabajo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** EP-TAL-01: Abrir orden de trabajo */
        post: operations["abrir_ot_v1_ordenes_trabajo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ordenes-trabajo/{ot_id}/repuestos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** EP-TAL-02: Agregar repuesto a orden de trabajo */
        post: operations["agregar_repuesto_v1_ordenes_trabajo__ot_id__repuestos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ordenes-trabajo/{ot_id}/aprobar-lista": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** EP-TAL-03: Aprobar lista → EN_EJECUCION */
        post: operations["aprobar_lista_v1_ordenes_trabajo__ot_id__aprobar_lista_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ordenes-trabajo/{ot_id}/confirmar-adicional": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** EP-TAL-04: Cliente confirma costo adicional manual */
        post: operations["confirmar_adicional_v1_ordenes_trabajo__ot_id__confirmar_adicional_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ordenes-trabajo/{ot_id}/autorizar-precio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** EP-TAL-05: Autorizar visibilidad de precio al cliente */
        post: operations["autorizar_precio_v1_ordenes_trabajo__ot_id__autorizar_precio_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ordenes-trabajo/{ot_id}/revision-final": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** EP-TAL-06: Declarar revisión final → REVISION_FINAL */
        post: operations["revision_final_v1_ordenes_trabajo__ot_id__revision_final_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ordenes-trabajo/{ot_id}/cobro-parcial": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** EP-TAL-07: Registrar cobro parcial con excepción 80% */
        post: operations["cobro_parcial_v1_ordenes_trabajo__ot_id__cobro_parcial_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ordenes-trabajo/{ot_id}/cerrar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** EP-TAL-08: Cerrar orden de trabajo */
        post: operations["cerrar_ot_v1_ordenes_trabajo__ot_id__cerrar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ordenes-trabajo/{ot_id}/cancelar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** EP-TAL-09: Cancelar orden de trabajo */
        post: operations["cancelar_ot_v1_ordenes_trabajo__ot_id__cancelar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ordenes-trabajo/{ot_id}/liberar-vehiculo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** EP-TAL-10: Liberar vehículo tras prueba de ruta */
        post: operations["liberar_vehiculo_v1_ordenes_trabajo__ot_id__liberar_vehiculo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/taller/disponibilidad": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** EP-TAL-11: Consultar disponibilidad de mecánicos */
        get: operations["consultar_disponibilidad_v1_taller_disponibilidad_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ordenes-trabajo/{ot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** EP-TAL-12: Obtener orden de trabajo */
        get: operations["obtener_ot_v1_ordenes_trabajo__ot_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** EP-OBS-01: Métricas cuatro señales doradas */
        get: operations["metrics_v1_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/privacidad": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** EP-OBS-02: Política de privacidad */
        get: operations["politica_privacidad_v1_privacidad_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AbrirOTRequest */
        AbrirOTRequest: {
            /** Vehiculo Id */
            vehiculo_id: string;
            /** Mecanico Master Id */
            mecanico_master_id: string;
            modalidad: components["schemas"]["ModalidadIntervencion"];
            urgencia: components["schemas"]["NivelUrgencia"];
            /** Mecanico Junior Id */
            mecanico_junior_id?: string | null;
            /** Cliente Id */
            cliente_id?: string | null;
        };
        /** ActualizarEstadoRequest */
        ActualizarEstadoRequest: {
            estado: components["schemas"]["EstadoReabastecimiento"];
            /** Actor Id */
            actor_id: string;
        };
        /** ActualizarParametroRequest */
        ActualizarParametroRequest: {
            /** Valor */
            valor: unknown;
        };
        /** ActualizarPrecioRequest */
        ActualizarPrecioRequest: {
            /** Precio Venta */
            precio_venta: number | string;
        };
        /** AgregarRepuestoRequest */
        AgregarRepuestoRequest: {
            /** Codigo */
            codigo: string;
            /** Cantidad */
            cantidad: number;
        };
        /** AjusteRequest */
        AjusteRequest: {
            /** Cantidad */
            cantidad: number;
            /** Actor Id */
            actor_id: string;
            /**
             * Motivo
             * @default
             */
            motivo: string;
        };
        /** AutorizarPrecioRequest */
        AutorizarPrecioRequest: {
            /** Cliente Id */
            cliente_id: string;
        };
        /** CancelarOTRequest */
        CancelarOTRequest: {
            /** Motivo */
            motivo: string;
        };
        /** CancelarPedidoRequest */
        CancelarPedidoRequest: {
            /** Motivo */
            motivo: string;
            /**
             * Es Cliente
             * @default false
             */
            es_cliente: boolean;
        };
        /**
         * CategoriaRepuesto
         * @enum {string}
         */
        CategoriaRepuesto: "motor" | "transmision" | "frenos" | "electrico" | "carroceria" | "suspension" | "tecnico_especializado" | "consumible" | "otro";
        /** CobroParcialRequest */
        CobroParcialRequest: {
            /** Monto Pagado */
            monto_pagado: number | string;
            /** Plazo Dias */
            plazo_dias: number;
        };
        /** ConfirmarAdicionalRequest */
        ConfirmarAdicionalRequest: {
            /** Item Id */
            item_id: string;
        };
        /** ConsultarListaRequest */
        ConsultarListaRequest: {
            /** Codigos */
            codigos: string[];
            universo?: components["schemas"]["UniversoRepuesto"] | null;
        };
        /** CrearListaReservaRequest */
        CrearListaReservaRequest: {
            /** Cliente Id */
            cliente_id: string;
            /** Nombre */
            nombre?: string | null;
            /** Items */
            items: components["schemas"]["ItemListaRequest"][];
        };
        /** CrearMecanicoRequest */
        CrearMecanicoRequest: {
            /** Usuario Id */
            usuario_id: string;
            /** Nivel */
            nivel: string;
            /** Supervisor Id */
            supervisor_id?: string | null;
        };
        /** CrearPedidoRequest */
        CrearPedidoRequest: {
            /** Canal Origen */
            canal_origen: string;
            /** Items */
            items: components["schemas"]["ItemInput"][];
            /** Cliente Id */
            cliente_id?: string | null;
            /** Orden Trabajo Id */
            orden_trabajo_id?: string | null;
        };
        /** CrearReabastecimientoRequest */
        CrearReabastecimientoRequest: {
            /** Proveedor */
            proveedor: string;
            /** Items */
            items: components["schemas"]["ItemReabRequest"][];
            /**
             * Notas
             * @default
             */
            notas: string;
        };
        /** CrearRepuestoRequest */
        CrearRepuestoRequest: {
            /** Codigo */
            codigo: string;
            /** Nombre */
            nombre: string;
            universo: components["schemas"]["UniversoRepuesto"];
            /** Modelo */
            modelo: string;
            /** Año */
            "a\u00F1o": number;
            categoria: components["schemas"]["CategoriaRepuesto"];
            /** Precio Venta */
            precio_venta: number | string;
            /**
             * Descripcion
             * @default
             */
            descripcion: string;
        };
        /** CrearReservaRequest */
        CrearReservaRequest: {
            /** Cliente Id */
            cliente_id: string;
            /** Repuesto Id */
            repuesto_id: string;
            /** Cantidad */
            cantidad: number;
            segmento: components["schemas"]["SegmentoCliente"];
            /** Pedido Id */
            pedido_id?: string | null;
        };
        /** CrearUsuarioRequest */
        CrearUsuarioRequest: {
            /** Email */
            email: string;
            /** Nombre */
            nombre: string;
            /** Rol */
            rol: string;
            /** Password */
            password: string;
            /**
             * Consentimiento Privacidad
             * @default false
             */
            consentimiento_privacidad: boolean;
        };
        /** CrearVehiculoRequest */
        CrearVehiculoRequest: {
            /** Universo */
            universo: string;
            /** Modelo */
            modelo: string;
            /** Año */
            "a\u00F1o": number;
            /** Cliente Id */
            cliente_id?: string | null;
            /** Placa */
            placa?: string | null;
        };
        /** DarDeBajaRequest */
        DarDeBajaRequest: {
            /** Motivo */
            motivo: string;
        };
        /**
         * EstadoReabastecimiento
         * @enum {string}
         */
        EstadoReabastecimiento: "SOLICITADO" | "CONFIRMADO_PROVEEDOR" | "EN_TRANSITO" | "RECIBIDO" | "CANCELADO";
        /** GenerarComprobanteRequest */
        GenerarComprobanteRequest: {
            tipo: components["schemas"]["TipoComprobante"];
            /** Monto */
            monto: number | string;
            /** Emitido Por */
            emitido_por: string;
            /** Rol Emisor */
            rol_emisor: string;
            /** Ruc Cliente */
            ruc_cliente?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ItemInput */
        ItemInput: {
            /** Codigo */
            codigo: string;
            /** Cantidad */
            cantidad: number;
        };
        /** ItemListaRequest */
        ItemListaRequest: {
            /** Repuesto Id */
            repuesto_id: string;
            /** Codigo */
            codigo: string;
            /** Cantidad */
            cantidad: number;
            /** Precio Referencia */
            precio_referencia: number | string;
        };
        /** ItemReabRequest */
        ItemReabRequest: {
            /** Repuesto Id */
            repuesto_id: string;
            /** Codigo */
            codigo: string;
            /** Cantidad Solicitada */
            cantidad_solicitada: number;
            /** Precio Costo Unitario */
            precio_costo_unitario: number | string;
        };
        /** LiberarReservaRequest */
        LiberarReservaRequest: {
            /**
             * Motivo
             * @default LIBERADA_MANUAL
             */
            motivo: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MfaRequest */
        MfaRequest: {
            /** Mfa Session Token */
            mfa_session_token: string;
            /** Totp Code */
            totp_code: string;
        };
        /**
         * ModalidadIntervencion
         * @description Modalidad de la intervención sobre el vehículo (02 §1.3).
         * @enum {string}
         */
        ModalidadIntervencion: "preventivo" | "correctivo" | "diagnostico" | "soldadura";
        /**
         * NivelUrgencia
         * @enum {string}
         */
        NivelUrgencia: "alta" | "media" | "baja";
        /** RegistrarEnvioRequest */
        RegistrarEnvioRequest: {
            /** Empresa Encomienda */
            empresa_encomienda: string;
            /** Direccion Destino */
            direccion_destino: string;
        };
        /** RevisionFinalRequest */
        RevisionFinalRequest: {
            /** Costo Mano Obra */
            costo_mano_obra: number | string;
        };
        /**
         * SegmentoCliente
         * @enum {string}
         */
        SegmentoCliente: "CLIENTE_CONDUCTOR" | "CLIENTE_DISTRITO" | "CLIENTE_FLOTA_DUENO" | "CLIENTE_FLOTA_CONDUCTOR" | "CLIENTE_RURAL" | "CLIENTE_MOTOLINEAL";
        /**
         * TipoComprobante
         * @enum {string}
         */
        TipoComprobante: "boleta" | "factura" | "ticket";
        /** UmbralRequest */
        UmbralRequest: {
            /** Umbral Minimo */
            umbral_minimo: number;
            /** Actor Id */
            actor_id: string;
        };
        /**
         * UniversoRepuesto
         * @enum {string}
         */
        UniversoRepuesto: "mototaxi" | "motolineal";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mfa_v1_auth_mfa_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_parametros_v1_admin_parametros_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    actualizar_parametro_v1_admin_parametros__clave__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clave: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActualizarParametroRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_vehiculo_v1_admin_vehiculos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearVehiculoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_mecanico_v1_admin_mecanicos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearMecanicoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_usuario_v1_admin_usuarios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearUsuarioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    buscar_repuestos_v1_repuestos_get: {
        parameters: {
            query: {
                universo: components["schemas"]["UniversoRepuesto"];
                modelo?: string | null;
                "a\u00F1o"?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_repuesto_v1_repuestos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearRepuestoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_repuesto_v1_repuestos__codigo__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                codigo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dar_de_baja_repuesto_v1_repuestos__codigo__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                codigo: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DarDeBajaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    consultar_precio_v1_repuestos__codigo__precio_get: {
        parameters: {
            query?: {
                consultas_realizadas?: number;
                nivel_visibilidad?: number;
            };
            header?: never;
            path: {
                codigo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    actualizar_precio_v1_repuestos__codigo__precio_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                codigo: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActualizarPrecioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    historial_precio_v1_repuestos__codigo__historial_precio_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                codigo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    consultar_lista_codigos_v1_catalogo_repuestos_consulta_lista_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsultarListaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    consultar_stock_v1_stock__codigo__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                codigo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_stock_v1_stock_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    listar_movimientos_v1_stock__codigo__movimientos_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                codigo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ajustar_stock_v1_stock__codigo__ajuste_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                codigo: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AjusteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    actualizar_umbral_v1_stock__codigo__umbral_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                codigo: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UmbralRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_reabastecimiento_v1_reabastecimientos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearReabastecimientoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    actualizar_estado_reabastecimiento_v1_reabastecimientos__reab_id__estado_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reab_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActualizarEstadoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_reabastecimiento_v1_reabastecimientos__reab_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reab_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_pedidos_v1_pedidos_get: {
        parameters: {
            query?: {
                cliente_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_pedido_v1_pedidos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearPedidoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_pedido_v1_pedidos__pedido_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pedido_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirmar_pedido_v1_pedidos__pedido_id__confirmar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pedido_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancelar_pedido_v1_pedidos__pedido_id__cancelar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pedido_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelarPedidoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_reserva_v1_reservas_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearReservaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    liberar_reserva_v1_reservas__reserva_id__liberar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reserva_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LiberarReservaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    emitir_proforma_v1_pedidos__pedido_id__proforma_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pedido_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    registrar_envio_v1_pedidos__pedido_id__envio_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pedido_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrarEnvioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirmar_recepcion_v1_pedidos__pedido_id__confirmar_recepcion_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pedido_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    registrar_incidencia_v1_pedidos__pedido_id__incidencia_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pedido_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    solicitar_notificacion_repuesto_v1_notificaciones_repuesto_disponible_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    crear_lista_reserva_v1_lista_reserva_progresiva_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearListaReservaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    formalizar_lista_reserva_v1_lista_reserva_progresiva__lista_id__formalizar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lista_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generar_comprobante_v1_pedidos__pedido_id__comprobante_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pedido_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerarComprobanteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    aprobar_comprobante_v1_comprobantes__comprobante_id__aprobar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                comprobante_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    anular_comprobante_v1_comprobantes__comprobante_id__anular_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                comprobante_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    abrir_ot_v1_ordenes_trabajo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AbrirOTRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agregar_repuesto_v1_ordenes_trabajo__ot_id__repuestos_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgregarRepuestoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    aprobar_lista_v1_ordenes_trabajo__ot_id__aprobar_lista_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirmar_adicional_v1_ordenes_trabajo__ot_id__confirmar_adicional_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmarAdicionalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    autorizar_precio_v1_ordenes_trabajo__ot_id__autorizar_precio_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutorizarPrecioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revision_final_v1_ordenes_trabajo__ot_id__revision_final_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionFinalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cobro_parcial_v1_ordenes_trabajo__ot_id__cobro_parcial_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CobroParcialRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cerrar_ot_v1_ordenes_trabajo__ot_id__cerrar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancelar_ot_v1_ordenes_trabajo__ot_id__cancelar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelarOTRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    liberar_vehiculo_v1_ordenes_trabajo__ot_id__liberar_vehiculo_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    consultar_disponibilidad_v1_taller_disponibilidad_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    obtener_ot_v1_ordenes_trabajo__ot_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_v1_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    politica_privacidad_v1_privacidad_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    health_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
