"""
Puerto de persistencia del módulo stock (03 §8.1).
Protocol — domain nunca importa la implementación.
"""
from __future__ import annotations

from typing import Optional, Protocol

from src.stock.domain.models.stock import MovimientoStock, Reabastecimiento, StockRepuesto


class StockRepository(Protocol):
    async def guardar(self, stock: StockRepuesto) -> StockRepuesto: ...
    async def obtener_por_repuesto_id(self, repuesto_id: str) -> Optional[StockRepuesto]: ...
    async def obtener_por_codigo(self, codigo: str) -> Optional[StockRepuesto]: ...
    async def listar_todos(self) -> list[StockRepuesto]: ...
    async def actualizar(self, stock: StockRepuesto) -> StockRepuesto: ...
    async def obtener_movimientos(self, repuesto_id: str) -> list[MovimientoStock]: ...
    async def guardar_reabastecimiento(self, reab: Reabastecimiento) -> Reabastecimiento: ...
    async def obtener_reabastecimiento(self, reab_id: str) -> Optional[Reabastecimiento]: ...
    async def actualizar_reabastecimiento(self, reab: Reabastecimiento) -> Reabastecimiento: ...
