"""Puerto de persistencia del módulo pedidos (03 §8.1)."""
from __future__ import annotations

from typing import Optional, Protocol

from src.pedidos.domain.models.pedido import (
    Comprobante,
    DeudaActiva,
    Envio,
    ListaReservaProg,
    Pedido,
    Proforma,
    Reserva,
)


class PedidoRepository(Protocol):
    async def guardar(self, pedido: Pedido) -> Pedido: ...
    async def obtener_por_id(self, pedido_id: str) -> Optional[Pedido]: ...
    async def listar_todos(self) -> list[Pedido]: ...
    async def listar_por_cliente(self, cliente_id: str) -> list[Pedido]: ...
    async def actualizar(self, pedido: Pedido) -> Pedido: ...

    async def guardar_reserva(self, reserva: Reserva) -> Reserva: ...
    async def obtener_reserva(self, reserva_id: str) -> Optional[Reserva]: ...
    async def listar_reservas_por_repuesto(self, repuesto_id: str) -> list[Reserva]: ...
    async def actualizar_reserva(self, reserva: Reserva) -> Reserva: ...

    async def guardar_proforma(self, proforma: Proforma) -> Proforma: ...
    async def obtener_proforma(self, proforma_id: str) -> Optional[Proforma]: ...

    async def guardar_envio(self, envio: Envio) -> Envio: ...
    async def obtener_envio_por_pedido(self, pedido_id: str) -> Optional[Envio]: ...

    async def guardar_comprobante(self, comp: Comprobante) -> Comprobante: ...
    async def obtener_comprobante(self, comp_id: str) -> Optional[Comprobante]: ...
    async def actualizar_comprobante(self, comp: Comprobante) -> Comprobante: ...

    async def guardar_deuda(self, deuda: DeudaActiva) -> DeudaActiva: ...

    async def guardar_lista_reserva(self, lista: ListaReservaProg) -> ListaReservaProg: ...
    async def obtener_lista_reserva(self, lista_id: str) -> Optional[ListaReservaProg]: ...
    async def actualizar_lista_reserva(self, lista: ListaReservaProg) -> ListaReservaProg: ...
